export default data = [
    {
        "id": 1,
        "name": "single economy",
        "slug": "single-economy",
        "image1": "http://127.0.0.1:8001/media/room-1.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-2.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-3.jpeg",
        "price": "5000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. \r\n\r\nTo achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. \r\n\r\nThe new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 2,
        "name": "single basic",
        "slug": "single-basic",
        "image1": "http://127.0.0.1:8001/media/room-4.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-5.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-6.jpeg",
        "price": "5000.00",
        "size": "700",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words.\r\n\r\n If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 3,
        "name": "single standart",
        "slug": "single-standart",
        "image1": "http://127.0.0.1:8001/media/room-4_XDgAL0m.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-1_YSPEIPw.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-2_bTeTkRS.jpeg",
        "price": "4000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words.\r\n\r\n If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. \r\n\r\nThe European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 4,
        "name": "single deluxe",
        "slug": "single-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-10.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-3_TzhZG3h.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-1_jnhBVZv.jpeg",
        "price": "5000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 5,
        "name": "double economy",
        "slug": "double-economy",
        "image1": "http://127.0.0.1:8001/media/room-5_4Ktxuek.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-6_CB3KAuV.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-8.jpeg",
        "price": "7000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 6,
        "name": "double basic",
        "slug": "double-basic",
        "image1": "http://127.0.0.1:8001/media/room-11.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_cwuieQt.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-7.jpeg",
        "price": "7000.00",
        "size": "800",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 7,
        "name": "double standard",
        "slug": "double-standard",
        "image1": "http://127.0.0.1:8001/media/room-12.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_b1SNxp6.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-1_uxbdGyC.jpeg",
        "price": "8000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 8,
        "name": "double deluxe",
        "slug": "double-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-3_Dikxbng.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-2_e0OWbkZ.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-10_rkDY20l.jpeg",
        "price": "10000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 9,
        "name": "family economy",
        "slug": "family-economy",
        "image1": "http://127.0.0.1:8001/media/room-8_yS0WRq8.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-10_DEebIRm.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-4_QcELMnY.jpeg",
        "price": "8000.00",
        "size": "800",
        "capacity": 3,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 10,
        "name": "family basic",
        "slug": "family-basic",
        "image1": "http://127.0.0.1:8001/media/room-10_93jcr68.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_mxeLbgF.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-7_hkVeacs.jpeg",
        "price": "8000.00",
        "size": "500",
        "capacity": 4,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 11,
        "name": "family deluxe",
        "slug": "family-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-11_SZtIhNv.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-7_VSb4ryQ.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-9.jpeg",
        "price": "12000.00",
        "size": "900",
        "capacity": 6,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    }
[
    {
        "id": 1,
        "name": "single economy",
        "slug": "single-economy",
        "image1": "http://127.0.0.1:8001/media/room-1.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-2.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-3.jpeg",
        "price": "5000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. \r\n\r\nTo achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. \r\n\r\nThe new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 2,
        "name": "single basic",
        "slug": "single-basic",
        "image1": "http://127.0.0.1:8001/media/room-4.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-5.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-6.jpeg",
        "price": "5000.00",
        "size": "700",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words.\r\n\r\n If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 3,
        "name": "single standart",
        "slug": "single-standart",
        "image1": "http://127.0.0.1:8001/media/room-4_XDgAL0m.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-1_YSPEIPw.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-2_bTeTkRS.jpeg",
        "price": "4000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words.\r\n\r\n If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. \r\n\r\nThe European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 4,
        "name": "single deluxe",
        "slug": "single-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-10.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-3_TzhZG3h.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-1_jnhBVZv.jpeg",
        "price": "5000.00",
        "size": "600",
        "capacity": 1,
        "is_featured": false,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 5,
        "name": "double economy",
        "slug": "double-economy",
        "image1": "http://127.0.0.1:8001/media/room-5_4Ktxuek.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-6_CB3KAuV.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-8.jpeg",
        "price": "7000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 6,
        "name": "double basic",
        "slug": "double-basic",
        "image1": "http://127.0.0.1:8001/media/room-11.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_cwuieQt.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-7.jpeg",
        "price": "7000.00",
        "size": "800",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 7,
        "name": "double standard",
        "slug": "double-standard",
        "image1": "http://127.0.0.1:8001/media/room-12.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_b1SNxp6.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-1_uxbdGyC.jpeg",
        "price": "8000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 8,
        "name": "double deluxe",
        "slug": "double-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-3_Dikxbng.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-2_e0OWbkZ.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-10_rkDY20l.jpeg",
        "price": "10000.00",
        "size": "900",
        "capacity": 2,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 9,
        "name": "family economy",
        "slug": "family-economy",
        "image1": "http://127.0.0.1:8001/media/room-8_yS0WRq8.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-10_DEebIRm.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-4_QcELMnY.jpeg",
        "price": "8000.00",
        "size": "800",
        "capacity": 3,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 10,
        "name": "family basic",
        "slug": "family-basic",
        "image1": "http://127.0.0.1:8001/media/room-10_93jcr68.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-8_mxeLbgF.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-7_hkVeacs.jpeg",
        "price": "8000.00",
        "size": "500",
        "capacity": 4,
        "is_featured": false,
        "has_breakfast": false,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    },
    {
        "id": 11,
        "name": "family deluxe",
        "slug": "family-deluxe",
        "image1": "http://127.0.0.1:8001/media/room-11_SZtIhNv.jpeg",
        "image2": "http://127.0.0.1:8001/media/room-7_VSb4ryQ.jpeg",
        "image3": "http://127.0.0.1:8001/media/room-9.jpeg",
        "price": "12000.00",
        "size": "900",
        "capacity": 6,
        "is_featured": true,
        "has_breakfast": true,
        "details": "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. \r\n\r\nEveryone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages.\r\n\r\n The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family. \r\n\r\nTheir separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary."
    }
]